name: Test at push

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend
        uses: actions/checkout@v6.0.1

      - name: Setup Node
        uses: actions/setup-node@v6.1.0
        with: 
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test > test-logs.txt

      - name: Upload test
        uses: actions/upload-artifact@v6.0.0
        with:
          name: test_logs
          path: test-logs.txt

      - name: Show tests
        run: cat test-logs.txt

      - name: Show secret
        run: echo ${{secrets.YOLO}}
        
